- name: CIS Hardening
  hosts: all
  become: true

  tasks:
    - name: Update system packages (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update system packages (Amazon Linux)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "Amazon"

    - name: Disable Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
