name: Build Golden AMI

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Enables OIDC authentication
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_IAM_INSTANCE_PROFILE: ${{ secrets.AWS_IAM_INSTANCE_PROFILE }}
      AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
      AWS_SOURCE_AMAZON_AMI: ${{ secrets.AWS_SOURCE_AMAZON_AMI }}
      AWS_SOURCE_UBUNTU_AMI: ${{ secrets.AWS_SOURCE_UBUNTU_AMI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: Initialize Packer Plugins
        run: packer init packer/plugins.pkr.hcl

      - name: Validate File Existence
        run: |
          ls -lh ansible/playbooks/cis-hardening.yml || (echo "❌ Ansible playbook missing!" && exit 1)
          ls -lh packer/scripts/install_packages.sh || (echo "❌ Install script missing!" && exit 1)

      - name: Build Amazon Linux 3 AMI
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" \
            packer/templates/amazon-linux.pkr.hcl

      - name: Build Ubuntu 24.04 AMI
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" \
            packer/templates/ubuntu.pkr.hcl
