name: Build Golden AMIs

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: Initialize Packer Plugins
        run: packer init packer/plugins.pkr.hcl

      - name: Load SSH Key
        run: |
          mkdir -p ~/.ssh  # ✅ Ensure SSH directory exists
          echo "${{ secrets.PACKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get Instance IP
        run: |
          echo "Fetching instance IP..."
          INSTANCE_IP=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "Instance IP: $INSTANCE_IP"
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Test SSH Connection
        run: |
          echo "Checking SSH authentication manually..."
          ssh -v -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa ec2-user@${{ env.INSTANCE_IP }} || echo "❌ SSH Authentication Failed"

      - name: Build Amazon Linux 3 AMI
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_instance_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" \
            packer/templates/amazon-linux.pkr.hcl
