name: Build Golden AMIs

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: Initialize Packer Plugins
        run: packer init packer/plugins.pkr.hcl

      - name: Build Amazon Linux 3 AMI
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_AMAZON_AMI }}" \
            packer/templates/amazon-linux.pkr.hcl

      - name: Build Ubuntu 24.04 AMI
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "iam_profile=${{ secrets.AWS_IAM_INSTANCE_PROFILE }}" \
            -var "source_ami=${{ secrets.AWS_SOURCE_UBUNTU_AMI }}" \
            packer/templates/ubuntu.pkr.hcl
